name: opensub2vec
channels:
    - conda-forge
dependencies:
    - python=3.6.7
    - pylint
    - autopep8
    - gensim=3.7.3
    - scikit-learn
    - matplotlib
    # - python-annoy
    - spacy
    - pyemd
    - flask
    - flask-cors
    - python-levenshtein
